name: FamilyBooks
options:
  bundleIdPrefix: com.familybooks
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 11.6.0

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "5824UP464U"

targets:
  FamilyBooks:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: Firebase
        product: FirebaseDatabase
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.familybooks.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Family Books
        UILaunchScreen: {}
        NSCameraUsageDescription: "We need camera access to scan book barcodes"
        ITSAppUsesNonExemptEncryption: false
